export const TEAL = "#1a3a3a";
export const ACCENT = "#e8472a";
export const LIGHT_TEAL = "#e8f5f0";

export const styles = {
  root: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    background: "#f5f4f1",
    overflow: "hidden",
    fontSize: "13px",
    color: "#1a1a1a",
  },
  topBanner: {
    background: TEAL,
    color: "#fff",
    textAlign: "center",
    padding: "8px 16px",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    flexShrink: 0,
    position: "relative",
  },
  bannerClose: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    color: "#fff",
    cursor: "pointer",
    fontSize: "16px",
    lineHeight: 1,
    opacity: 0.7,
  },
  navbar: {
    background: TEAL,
    display: "flex",
    alignItems: "center",
    padding: "0 16px",
    height: "48px",
    gap: "12px",
    flexShrink: 0,
  },
  navLogo: {
    color: "#fff",
    fontWeight: 700,
    fontSize: "16px",
    letterSpacing: "-0.3px",
    display: "flex",
    alignItems: "center",
    gap: "2px",
  },
  logoStar: { color: ACCENT, fontSize: "18px" },
  navBreadcrumb: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginLeft: "8px",
  },
  breadcrumbPill: {
    background: "rgba(255,255,255,0.15)",
    color: "#fff",
    borderRadius: "20px",
    padding: "3px 12px",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  navRight: { marginLeft: "auto", display: "flex", alignItems: "center", gap: "12px" },
  navIcon: {
    background: "none",
    border: "none",
    color: "rgba(255,255,255,0.7)",
    cursor: "pointer",
    padding: "6px",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
  },
  body: { display: "flex", flex: 1, overflow: "hidden" },
  sidebar: {
    width: "48px",
    background: "#fff",
    borderRight: "1px solid #e5e3df",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: "8px",
    gap: "4px",
    flexShrink: 0,
  },
  sidebarBtn: {
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    background: "none",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#666",
    fontSize: "16px",
    transition: "background 0.15s",
  },
  sidebarBtnActive: { background: LIGHT_TEAL, color: TEAL },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "#fff",
    borderRight: "1px solid #e5e3df",
  },
  chatArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
    overflow: "auto",
  },
  chatTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "8px",
  },
  chatTitleStar: { color: ACCENT, fontSize: "28px" },
  chatTitleText: { fontSize: "24px", fontWeight: 700, color: "#111", letterSpacing: "-0.5px" },
  chatSubtitle: { color: "#888", fontSize: "13px", marginBottom: "0" },
  messagesContainer: {
    flex: 1,
    width: "100%",
    maxWidth: "720px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    overflowY: "auto",
    marginTop: "16px",
  },
  msgUser: {
    alignSelf: "flex-end",
    background: TEAL,
    color: "#fff",
    borderRadius: "12px 12px 2px 12px",
    padding: "8px 14px",
    maxWidth: "70%",
    fontSize: "13px",
    lineHeight: 1.5,
  },
  msgAssistant: {
    alignSelf: "flex-start",
    background: "#f5f4f1",
    color: "#1a1a1a",
    borderRadius: "12px 12px 12px 2px",
    padding: "8px 14px",
    maxWidth: "80%",
    fontSize: "13px",
    lineHeight: 1.5,
    border: "1px solid #e5e3df",
  },
  inputArea: {
    padding: "12px 16px 16px",
    borderTop: "1px solid #ece9e4",
    background: "#fff",
  },
  suggestRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "8px",
    overflowX: "auto",
    paddingBottom: "4px",
  },
  tryLabel: {
    color: "#aaa",
    fontSize: "11px",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  suggestChip: {
    background: "#f5f4f1",
    border: "1px solid #e5e3df",
    borderRadius: "20px",
    padding: "4px 12px",
    fontSize: "11px",
    color: "#444",
    cursor: "pointer",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  chipIcon: { fontSize: "12px" },
  inputBox: {
    border: "1.5px solid #ddd",
    borderRadius: "10px",
    background: "#fff",
    display: "flex",
    alignItems: "flex-end",
    gap: "8px",
    padding: "8px 12px",
    transition: "border-color 0.15s",
  },
  inputBoxFocused: { borderColor: TEAL },
  inputEl: {
    flex: 1,
    border: "none",
    outline: "none",
    resize: "none",
    fontSize: "13px",
    lineHeight: 1.5,
    background: "transparent",
    color: "#1a1a1a",
    fontFamily: "inherit",
    minHeight: "20px",
    maxHeight: "120px",
  },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#999",
    padding: "2px",
    display: "flex",
    alignItems: "center",
    fontSize: "16px",
    borderRadius: "6px",
  },
  sendBtn: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    transition: "background 0.15s",
    flexShrink: 0,
  },
  disclaimer: {
    textAlign: "center",
    fontSize: "11px",
    color: "#888",
    marginTop: "8px",
    lineHeight: 1.4,
  },
  disclaimerAccent: { color: ACCENT, fontWeight: 600 },
  rightPanel: {
    width: "340px",
    background: "#fff",
    borderLeft: "1px solid #e5e3df",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    flexShrink: 0,
  },
  panelHeader: {
    padding: "12px 16px",
    borderBottom: "1px solid #ece9e4",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "#fafaf8",
  },
  panelTab: {
    padding: "6px 14px",
    borderRadius: "20px",
    border: "none",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
    transition: "background 0.15s",
  },
  panelTabActive: { background: TEAL, color: "#fff" },
  panelTabInactive: { background: "transparent", color: "#666" },
  panelBody: { flex: 1, overflowY: "auto", padding: "16px" },
  section: { marginBottom: "20px" },
  sectionLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: "0.6px",
    marginBottom: "8px",
  },
  row: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "8px" },
  toggle: { position: "relative", display: "inline-block", width: "36px", height: "20px" },
  toggleInput: { opacity: 0, width: 0, height: 0, position: "absolute" },
  toggleSlider: (on) => ({
    position: "absolute",
    inset: 0,
    borderRadius: "20px",
    background: on ? TEAL : "#d0cec9",
    cursor: "pointer",
    transition: "background 0.2s",
  }),
  toggleThumb: (on) => ({
    position: "absolute",
    width: "14px",
    height: "14px",
    borderRadius: "50%",
    background: "#fff",
    top: "3px",
    left: on ? "19px" : "3px",
    transition: "left 0.2s",
  }),
  checkbox: {
    width: "14px",
    height: "14px",
    accentColor: TEAL,
    cursor: "pointer",
  },
  labelRow: { display: "flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "#333" },
  outlineBtn: {
    width: "100%",
    border: "1px solid #ddd",
    borderRadius: "8px",
    background: "#fafaf8",
    padding: "8px 12px",
    fontSize: "12px",
    color: "#444",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    marginBottom: "6px",
    transition: "border-color 0.15s, background 0.15s",
  },
  halfBtn: {
    flex: 1,
    border: "1px solid #ddd",
    borderRadius: "8px",
    background: "#fafaf8",
    padding: "8px",
    fontSize: "12px",
    color: "#444",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
  },
  fieldLabel: { fontSize: "11px", color: "#888", marginBottom: "4px", fontWeight: 500 },
  fieldInput: {
    width: "100%",
    border: "1px solid #e0ddd8",
    borderRadius: "8px",
    padding: "7px 10px",
    fontSize: "12px",
    color: "#222",
    background: "#fff",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    marginBottom: "10px",
    transition: "border-color 0.15s",
  },
  textarea: {
    width: "100%",
    border: "1px solid #e0ddd8",
    borderRadius: "8px",
    padding: "8px 10px",
    fontSize: "12px",
    color: "#222",
    background: "#fff",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    resize: "vertical",
    minHeight: "90px",
    lineHeight: 1.5,
    transition: "border-color 0.15s",
  },
  agentIdText: { fontSize: "10px", color: "#aaa", marginTop: "-8px", marginBottom: "10px" },
  panelFooter: {
    borderTop: "1px solid #ece9e4",
    padding: "12px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    background: "#fafaf8",
  },
  footerBtnRow: { display: "flex", alignItems: "center", gap: "8px" },
  dangerBtn: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: "1px solid #e8d0cc",
    background: "#fdf0ed",
    color: ACCENT,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
  },
  ghostBtn: {
    height: "32px",
    borderRadius: "8px",
    border: "1px solid #e0ddd8",
    background: "#fff",
    color: "#444",
    cursor: "pointer",
    padding: "0 12px",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
  saveBtn: {
    flex: 1,
    height: "32px",
    borderRadius: "8px",
    border: "none",
    background: TEAL,
    color: "#fff",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 600,
    letterSpacing: "0.2px",
  },
  menuList: { listStyle: "none", margin: 0, padding: 0 },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "8px 10px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "12px",
    color: "#444",
    marginBottom: "2px",
    transition: "background 0.12s",
  },
  agentDropdown: {
    width: "100%",
    border: "1px solid #e0ddd8",
    borderRadius: "8px",
    padding: "8px 10px",
    fontSize: "13px",
    color: "#222",
    background: "#fff",
    outline: "none",
    fontFamily: "inherit",
    marginBottom: "12px",
    cursor: "pointer",
  },
  avatarCircle: {
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    border: "2px dashed #c8c4be",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#aaa",
    fontSize: "20px",
    margin: "0 auto 16px",
  },
  createAgentRow: { display: "flex", gap: "8px", marginBottom: "16px" },
  createBtn: {
    flex: 1,
    border: "1px solid #e0ddd8",
    borderRadius: "8px",
    background: "#fafaf8",
    padding: "7px 10px",
    fontSize: "12px",
    color: "#444",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  selectBtn: {
    border: "none",
    borderRadius: "8px",
    background: TEAL,
    color: "#fff",
    padding: "7px 16px",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  modelDisplay: {
    border: "1px solid #e0ddd8",
    borderRadius: "8px",
    padding: "8px 10px",
    fontSize: "12px",
    color: "#444",
    background: "#fafaf8",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "10px",
  },
  modelIcon: { fontSize: "14px" },
  chatSidebar: {
    width: "268px",
    background: "#fafaf8",
    borderRight: "1px solid #e5e3df",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    overflow: "hidden",
  },
  chatSidebarToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    padding: "10px 8px",
    borderBottom: "1px solid #ece9e4",
    background: "#fff",
    flexShrink: 0,
  },
  chatSidebarList: {
    flex: 1,
    overflowY: "auto",
    padding: "8px",
    minHeight: 0,
  },
  chatSidebarEmpty: {
    fontSize: "12px",
    color: "#999",
    textAlign: "center",
    padding: "16px 8px",
    lineHeight: 1.5,
  },
  chatSessionRow: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "8px 8px 8px 10px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "2px",
    border: "1px solid transparent",
    transition: "background 0.12s, border-color 0.12s",
  },
  chatSessionRowActive: {
    background: LIGHT_TEAL,
    borderColor: "#c5ddd4",
  },
  chatSessionRowArchived: { opacity: 0.75 },
  chatSessionTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: "13px",
    fontWeight: 500,
    color: "#222",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chatSessionTitleInput: {
    flex: 1,
    minWidth: 0,
    fontSize: "13px",
    fontWeight: 500,
    color: "#222",
    fontFamily: "inherit",
    padding: "4px 8px",
    border: "1px solid " + TEAL,
    borderRadius: "6px",
    outline: "none",
    background: "#fff",
    boxSizing: "border-box",
  },
  chatRowMenuWrap: { position: "relative", flexShrink: 0 },
  chatRowMenuBtn: {
    width: "28px",
    height: "28px",
    border: "none",
    background: "transparent",
    borderRadius: "6px",
    cursor: "pointer",
    color: "#888",
    fontSize: "16px",
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  chatDropdown: {
    position: "absolute",
    right: 0,
    top: "100%",
    marginTop: "2px",
    minWidth: "152px",
    background: "#fff",
    border: "1px solid #e5e3df",
    borderRadius: "8px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.08)",
    zIndex: 100,
    padding: "4px 0",
  },
  chatDropdownItem: {
    display: "block",
    width: "100%",
    textAlign: "left",
    border: "none",
    background: "none",
    fontSize: "12px",
    color: "#333",
    padding: "8px 12px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  chatSidebarSectionLabel: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#aaa",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    padding: "10px 8px 4px",
  },
};
